version: '3.9'

services:
  pgvector:
    image: pgvector/pgvector:pg16
    shm_size: 128mb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: monsterapi
      POSTGRES_PASSWORD: monsterapipassword
      POSTGRES_DB: neodbdev
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql